import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/services/database_service.dart';
import '../../../../core/services/firebase_service.dart';
import '../../../../core/services/active_profile_controller.dart';

class NotificationsScreen extends StatelessWidget{
 const NotificationsScreen({super.key});
 @override Widget build(BuildContext context){final real=FirebaseAuth.instance.currentUser;if(!FirebaseService.initialized||real==null)return Scaffold(appBar:AppBar(title:const Text('Notifications')),body:const Center(child:Text('Sign in to view notifications.')));final db=DatabaseService();final demo=ActiveProfileController.instance.isDemo;if(demo)return Scaffold(appBar:AppBar(title:Text('${ActiveProfileController.instance.effectiveName} • Notifications')),body:StreamBuilder<List<Map<String,dynamic>>>(stream:db.demoNotificationsStream(real.uid),builder:(context,s)=>_list(context,s.data??const [])));return Scaffold(appBar:AppBar(title:const Text('Notifications')),body:StreamBuilder(stream:db.notificationsStream(real.uid),builder:(context,AsyncSnapshot snap){final docs=snap.data?.docs??[];return _firebaseList(context,docs,db,real.uid);}));}
 Widget _list(BuildContext context,List<Map<String,dynamic>> docs)=>docs.isEmpty?const Center(child:Text('No notifications yet.')):ListView.separated(padding:const EdgeInsets.all(12),itemCount:docs.length,separatorBuilder:(_,__)=>const SizedBox(height:6),itemBuilder:(_,i){final x=docs[i];final read=x['read']==true;final postId=(x['postId']??'').toString();return Card(color:read?null:const Color(0xFFEAF8F2),child:ListTile(leading:const CircleAvatar(child:Icon(Icons.notifications_none)),title:Text(x['text']?.toString()??'Activity',style:TextStyle(fontWeight:read?FontWeight.normal:FontWeight.w700)),subtitle:Text(read?'Read':'New notification'),onTap:()async{await DatabaseService().markNotificationRead(ActiveProfileController.instance.effectiveUid??'',x['id'].toString());if(postId.isNotEmpty&&context.mounted)context.push('/community/post/$postId');}));});
 Widget _firebaseList(BuildContext context,List docs,DatabaseService db,String uid)=>docs.isEmpty?const Center(child:Text('No notifications yet.')):ListView.separated(padding:const EdgeInsets.all(12),itemCount:docs.length,separatorBuilder:(_,__)=>const SizedBox(height:6),itemBuilder:(_,i){final d=docs[i];final x=d.data() as Map<String,dynamic>;final read=x['read']==true;final postId=(x['postId']??'').toString();return Card(color:read?null:const Color(0xFFEAF8F2),child:ListTile(leading:const CircleAvatar(child:Icon(Icons.notifications_none)),title:Text((x['text']??'Activity').toString(),style:TextStyle(fontWeight:read?FontWeight.normal:FontWeight.w700)),subtitle:Text(read?'Read':'New notification'),onTap:()async{await db.markNotificationRead(uid,d.id);if(postId.isNotEmpty&&context.mounted)context.push('/community/post/$postId');}));});
}