import 'package:flutter/material.dart';

class Job {
  final String title, company, location, field, mode, salary, experience, deadline, description;
  final List<String> requirements;
  const Job({required this.title, required this.company, required this.location, required this.field, required this.mode, required this.salary, required this.experience, required this.deadline, required this.description, required this.requirements});
}

class JobsScreen extends StatefulWidget {
  const JobsScreen({super.key});
  @override State<JobsScreen> createState() => _JobsScreenState();
}

class _JobsScreenState extends State<JobsScreen> {
  final _search=TextEditingController();
  String _field='All', _mode='All';
  final List<Job> _jobs=const [
    Job(title:'Junior Flutter Developer',company:'TechNova Solutions',location:'Lahore',field:'Software',mode:'Hybrid',salary:'Rs. 70,000 - 100,000',experience:'0-1 year',deadline:'30 Nov 2026',description:'Build and maintain mobile applications with a product-focused development team.',requirements:['Flutter/Dart knowledge','Git basics','Good problem-solving skills']),
    Job(title:'UI/UX Designer',company:'PixelCraft Studio',location:'Lahore',field:'Design',mode:'On-site',salary:'Rs. 60,000 - 90,000',experience:'1-2 years',deadline:'15 Dec 2026',description:'Create intuitive interfaces, prototypes and design systems for digital products.',requirements:['Figma','UI/UX fundamentals','Portfolio']),
    Job(title:'Digital Marketing Executive',company:'GrowthHub',location:'Remote',field:'Marketing',mode:'Remote',salary:'Rs. 55,000 - 80,000',experience:'1-2 years',deadline:'10 Dec 2026',description:'Plan and execute digital campaigns, content and social media activities.',requirements:['Digital marketing knowledge','Communication skills','Analytics basics']),
    Job(title:'Accounts Officer',company:'Prime Advisory',location:'Islamabad',field:'Finance',mode:'On-site',salary:'Rs. 65,000 - 85,000',experience:'1-2 years',deadline:'05 Dec 2026',description:'Handle financial records, reporting and day-to-day accounting operations.',requirements:['Accounting fundamentals','Excel','B.Com/ACCA preferred']),
    Job(title:'Electrical Engineer',company:'PowerTech Industries',location:'Multan',field:'Engineering',mode:'On-site',salary:'Rs. 90,000 - 130,000',experience:'2-3 years',deadline:'20 Dec 2026',description:'Support industrial engineering projects, maintenance and technical documentation.',requirements:['Engineering degree','Technical knowledge','Safety awareness']),
    Job(title:'Backend Developer',company:'CodeWorks',location:'Remote',field:'Software',mode:'Remote',salary:'Rs. 100,000 - 150,000',experience:'1-2 years',deadline:'25 Nov 2026',description:'Develop APIs and backend services with a focus on reliable and scalable systems.',requirements:['REST APIs','Node.js or similar','Database fundamentals']),
  ];
  List<Job> get _filtered { final q=_search.text.toLowerCase().trim(); return _jobs.where((x)=>(q.isEmpty||'${x.title} ${x.company} ${x.location} ${x.field}'.toLowerCase().contains(q))&&(_field=='All'||x.field==_field)&&(_mode=='All'||x.mode==_mode)).toList(); }
  void _details(Job x){showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(20,4,20,24),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.title,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),Text(x.company,style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:[_chip(Icons.location_on_outlined,x.location),_chip(Icons.laptop_mac_outlined,x.mode),_chip(Icons.payments_outlined,x.salary),_chip(Icons.work_history_outlined,x.experience)]),const SizedBox(height:20),Text('Job description',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),Text(x.description),const SizedBox(height:18),Text('Requirements',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),...x.requirements.map((r)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.check_circle_outline),title:Text(r))),Text('Application deadline: ${x.deadline}',style:const TextStyle(fontWeight:FontWeight.w600)),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.send_outlined),label:const Text('Apply Now')))]))));}
  Widget _chip(IconData i,String t)=>Chip(avatar:Icon(i,size:17),label:Text(t));
  void _filters(){showModalBottomSheet(context:context,showDragHandle:true,builder:(_)=>StatefulBuilder(builder:(c,setSheet)=>Padding(padding:const EdgeInsets.fromLTRB(20,4,20,24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Filter jobs',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:16),Text('Work mode',style:Theme.of(context).textTheme.titleMedium),Wrap(spacing:8,children:['All','Remote','Hybrid','On-site'].map((v)=>ChoiceChip(label:Text(v),selected:_mode==v,onSelected:(_){setSheet((){});setState(()=>_mode=v);})).toList()),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('Apply Filters')))])));}
  @override Widget build(BuildContext context){final data=_filtered;return Scaffold(appBar:AppBar(title:const Text('Jobs'),actions:[IconButton(onPressed:_filters,icon:const Icon(Icons.tune))]),body:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,8,16,12),child:TextField(controller:_search,onChanged:(_)=>setState((){}),decoration:InputDecoration(hintText:'Search jobs, companies...',prefixIcon:const Icon(Icons.search),suffixIcon:_search.text.isEmpty?null:IconButton(onPressed:()=>setState(()=>_search.clear()),icon:const Icon(Icons.clear)),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16))))),SingleChildScrollView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:16),child:Row(children:['All','Software','Design','Marketing','Finance','Engineering'].map((v)=>Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(v),selected:_field==v,onSelected:(_)=>setState(()=>_field=v)))).toList())),Padding(padding:const EdgeInsets.fromLTRB(16,14,16,8),child:Row(children:[Text('${data.length} jobs',style:const TextStyle(fontWeight:FontWeight.w600)),const Spacer(),if(_mode!='All')TextButton(onPressed:()=>setState(()=>_mode='All'),child:const Text('Clear filter'))])),Expanded(child:data.isEmpty?const Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.work_off_outlined,size:56),SizedBox(height:12),Text('No jobs found'),SizedBox(height:4),Text('Try changing your search or filters.')])):ListView.builder(padding:const EdgeInsets.fromLTRB(16,4,16,24),itemCount:data.length,itemBuilder:(_,i){final x=data[i];return Card(margin:const EdgeInsets.only(bottom:12),child:InkWell(borderRadius:BorderRadius.circular(16),onTap:()=>_details(x),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Text(x.title,style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold))),const Icon(Icons.chevron_right)]),const SizedBox(height:5),Text(x.company),const SizedBox(height:12),Wrap(spacing:6,runSpacing:6,children:[Chip(label:Text(x.field)),Chip(label:Text(x.mode)),Chip(label:Text(x.salary))]),const SizedBox(height:6),Row(children:[const Icon(Icons.location_on_outlined,size:17),const SizedBox(width:4),Text(x.location),const Spacer(),Text('Due ${x.deadline}',style:Theme.of(context).textTheme.bodySmall)])]))));}))]);}
}