import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../../core/services/database_service.dart';
import '../../../../core/services/active_profile_controller.dart';

class GroupsScreen extends StatelessWidget{
 const GroupsScreen({super.key});
 @override Widget build(BuildContext context){final user=FirebaseAuth.instance.currentUser;if(user==null)return const Center(child:Text('Please sign in to use groups.'));final db=DatabaseService();if(ActiveProfileController.instance.isDemo)return Scaffold(appBar:AppBar(title:const Text('Study Groups')),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_createDemo(context,user.uid),icon:const Icon(Icons.add),label:const Text('Create Group')),body:StreamBuilder<List<Map<String,dynamic>>>(stream:db.demoGroupsStream(),builder:(context,s)=>_demoList(context,s.data??const [])));final ref=FirebaseFirestore.instance.collection('studyGroups');return Scaffold(appBar:AppBar(title:const Text('Study Groups')),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_createFirebase(context,user.uid,ref),icon:const Icon(Icons.add),label:const Text('Create Group')),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:ref.orderBy('createdAt',descending:true).limit(50).snapshots(),builder:(context,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());final docs=s.data?.docs??[];return ListView.builder(padding:const EdgeInsets.all(12),itemCount:docs.length,itemBuilder:(context,i){final d=docs[i].data();return Card(child:ListTile(title:Text((d['name']??'Study Group').toString()),subtitle:Text((d['description']??'').toString()),trailing:Text('${d['memberCount']??1} members'),onTap:()=>_joinFirebase(context,docs[i].id,user.uid)));});}));}
 Widget _demoList(BuildContext context,List<Map<String,dynamic>> groups)=>groups.isEmpty?const Center(child:Text('No study groups yet.')):ListView.builder(padding:const EdgeInsets.all(12),itemCount:groups.length,itemBuilder:(context,i){final g=groups[i];return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.groups_outlined)),title:Text(g['name'].toString(),style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(g['description'].toString()),trailing:Text('${g['memberCount']} members'),onTap:()async{await DatabaseService().joinDemoGroup(g['id'].toString());if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Joined study group.')));}));});
 Future<void> _createDemo(BuildContext context,String uid)async{final v=await _form(context);if(v!=null)await DatabaseService().createDemoGroup(uid,v.$1,v.$2);}
 Future<void> _createFirebase(BuildContext context,String uid,CollectionReference<Map<String,dynamic>> ref)async{final v=await _form(context);if(v!=null)await ref.add({'name':v.$1,'description':v.$2,'ownerId':uid,'memberCount':1,'createdAt':FieldValue.serverTimestamp()});}
 Future<(String,String)?> _form(BuildContext context)async{final n=TextEditingController(),d=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Create Study Group'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Group name')),TextField(controller:d,decoration:const InputDecoration(labelText:'Description'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Create'))]));final v=ok==true&&n.text.trim().isNotEmpty?(n.text.trim(),d.text.trim()):null;n.dispose();d.dispose();return v;}
 static Future<void> _joinFirebase(BuildContext context,String id,String uid)async{await FirebaseFirestore.instance.collection('studyGroups').doc(id).update({'memberCount':FieldValue.increment(1)});if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Joined study group.')));}
}